import=["~/.cache/wal/colors-alacritty.toml"]

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window.padding]
x = 20
y = 20

[window]
opacity = 0.8
blur = true